### ISSUE TITLE
Packages do NPM com TypeScript

### ISSUE THREAD

**Issue by friaca** [abnerfs/abner-pro-grammer-channel#1]
Quero criar packages pra publicar no npm com TypeScript mas não sei como, seria bem legal um vídeo ensinando a fazer todo o processo desde escrever o código, publicar o necessário e exemplificar a integração do package em outro projeto.

**Comment by abnerfs** [comment]
Obrigado pela sugestão, vou preparar um vídeo pra gravar no fim de semana

**Comment by abnerfs** [comment]
https://www.youtube.com/watch?v=N2hwU51vWEs
